//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeminiLab.Glos.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeminiLab.Glos.i18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operand type &quot;{1}&quot; and &quot;{2}&quot; for operator &quot;{0}&quot;..
        /// </summary>
        internal static string DefaultMessageGlosInvalidBinaryOperandTypeException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosInvalidBinaryOperandTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid program counter..
        /// </summary>
        internal static string DefaultMessageGlosInvalidInstructionPointerException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosInvalidInstructionPointerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operand type &quot;{1}&quot; for operator &quot;{0}&quot;..
        /// </summary>
        internal static string DefaultMessageGlosInvalidUnaryOperandTypeException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosInvalidUnaryOperandTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of requested local variable ({0}) out of range..
        /// </summary>
        internal static string DefaultMessageGlosLocalVariableIndexOutOfRangeException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosLocalVariableIndexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A runtime exception occurred during execution..
        /// </summary>
        internal static string DefaultMessageGlosRuntimeException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosRuntimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurred during execution. Inner exception message: {1}..
        /// </summary>
        internal static string DefaultMessageGlosRuntimeExceptionWithInner {
            get {
                return ResourceManager.GetString("DefaultMessageGlosRuntimeExceptionWithInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of code..
        /// </summary>
        internal static string DefaultMessageGlosUnexpectedEndOfCodeException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosUnexpectedEndOfCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown op 0x{0:x2}..
        /// </summary>
        internal static string DefaultMessageGlosUnknownOpException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosUnknownOpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not callable..
        /// </summary>
        internal static string DefaultMessageGlosValueNotCallableException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosValueNotCallableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type assertion failed: {0} expected, {1} get..
        /// </summary>
        internal static string DefaultMessageGlosValueTypeAssertionFailedException {
            get {
                return ResourceManager.GetString("DefaultMessageGlosValueTypeAssertionFailedException", resourceCulture);
            }
        }
    }
}
