//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeminiLab.Glug.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeminiLab.Glug.i18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment to unassignable expression at {0}.
        /// </summary>
        internal static string DefaultMessageGlugAssignToUnassignableExpressionException {
            get {
                return ResourceManager.GetString("DefaultMessageGlugAssignToUnassignableExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation error at {0}.
        /// </summary>
        internal static string DefaultMessageGlugCompilingException {
            get {
                return ResourceManager.GetString("DefaultMessageGlugCompilingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangling break at {0}.
        /// </summary>
        internal static string DefaultMessageGlugDanglingBreakException {
            get {
                return ResourceManager.GetString("DefaultMessageGlugDanglingBreakException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation of pseudo expression at {0}.
        /// </summary>
        internal static string DefaultMessageGlugEvaluationOfPseudoExpressionException {
            get {
                return ResourceManager.GetString("DefaultMessageGlugEvaluationOfPseudoExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of token stream, last token at {0}.
        /// </summary>
        internal static string DefaultMessageGlugUnexpectedEndOfTokenStreamException {
            get {
                return ResourceManager.GetString("DefaultMessageGlugUnexpectedEndOfTokenStreamException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of token stream.
        /// </summary>
        internal static string DefaultMessageGlugUnexpectedEndOfTokenStreamExceptionNoLastToken {
            get {
                return ResourceManager.GetString("DefaultMessageGlugUnexpectedEndOfTokenStreamExceptionNoLastToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token: {0}, [{1}] expected.
        /// </summary>
        internal static string DefaultMessageGlugUnexpectedTokenException {
            get {
                return ResourceManager.GetString("DefaultMessageGlugUnexpectedTokenException", resourceCulture);
            }
        }
    }
}
