namespace GeminiLab.Glos.ViMa {

    public enum GlosOpCategory : byte {
        NotUsed,
        BinaryArithmeticOperator,
        BinaryBitwiseOperator,
        BinaryComparisonOperator,
        TableOperator,
        UnaryOperator,
        LoadInteger,
        LoadLocalVariable,
        StoreLocalVariable,
        LoadArgument,
        Branch,
        ShpRv,
        Syscall,
        Others,
    }

    public enum GlosOpImmediate : byte {
        None,
        Embedded,
        Byte,
        Word,
        Dword,
        Qword,
        OnStack,
    }

    public static class GlosOpInfo {
        public static GlosOpCategory[] Categories { get; } = {
            // 0x00
            GlosOpCategory.BinaryArithmeticOperator, 
            GlosOpCategory.BinaryArithmeticOperator, 
            GlosOpCategory.BinaryArithmeticOperator, 
            GlosOpCategory.BinaryArithmeticOperator,
            GlosOpCategory.BinaryArithmeticOperator,
            GlosOpCategory.BinaryBitwiseOperator, 
            GlosOpCategory.BinaryBitwiseOperator, 
            GlosOpCategory.BinaryBitwiseOperator,
            // 0x08
            GlosOpCategory.BinaryBitwiseOperator,
            GlosOpCategory.BinaryBitwiseOperator, 
            GlosOpCategory.BinaryComparisonOperator,
            GlosOpCategory.BinaryComparisonOperator,
            GlosOpCategory.BinaryComparisonOperator,
            GlosOpCategory.BinaryComparisonOperator,
            GlosOpCategory.BinaryComparisonOperator,
            GlosOpCategory.BinaryComparisonOperator, 
            // 0x10
            GlosOpCategory.TableOperator, 
            GlosOpCategory.TableOperator,
            GlosOpCategory.TableOperator,
            GlosOpCategory.TableOperator,
            GlosOpCategory.TableOperator,
            GlosOpCategory.TableOperator,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x18
            GlosOpCategory.UnaryOperator,
            GlosOpCategory.UnaryOperator,
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed,
            // 0x20
            GlosOpCategory.Others,
            GlosOpCategory.Others, 
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x28
            GlosOpCategory.Others,
            GlosOpCategory.Others, 
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.Others,
            GlosOpCategory.Others, 
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x30
            GlosOpCategory.LoadInteger, 
            GlosOpCategory.LoadInteger, 
            GlosOpCategory.LoadInteger, 
            GlosOpCategory.LoadInteger,
            GlosOpCategory.LoadInteger, 
            GlosOpCategory.LoadInteger, 
            GlosOpCategory.LoadInteger, 
            GlosOpCategory.LoadInteger,
            // 0x38
            GlosOpCategory.Others, 
            GlosOpCategory.Others, 
            GlosOpCategory.Others, 
            GlosOpCategory.NotUsed,
            GlosOpCategory.Others, 
            GlosOpCategory.Others, 
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed,
            // 0x40
            GlosOpCategory.LoadLocalVariable,
            GlosOpCategory.LoadLocalVariable,
            GlosOpCategory.LoadLocalVariable, 
            GlosOpCategory.LoadLocalVariable,
            GlosOpCategory.LoadLocalVariable, 
            GlosOpCategory.LoadLocalVariable, 
            GlosOpCategory.LoadLocalVariable, 
            GlosOpCategory.LoadLocalVariable,
            // 0x48
            GlosOpCategory.StoreLocalVariable, 
            GlosOpCategory.StoreLocalVariable,
            GlosOpCategory.StoreLocalVariable,
            GlosOpCategory.StoreLocalVariable,
            GlosOpCategory.StoreLocalVariable,
            GlosOpCategory.StoreLocalVariable,
            GlosOpCategory.StoreLocalVariable, 
            GlosOpCategory.StoreLocalVariable,
            // 0x50
            GlosOpCategory.LoadArgument,
            GlosOpCategory.LoadArgument,
            GlosOpCategory.LoadArgument,
            GlosOpCategory.LoadArgument,
            GlosOpCategory.LoadArgument,
            GlosOpCategory.LoadLocalVariable,
            GlosOpCategory.StoreLocalVariable,
            GlosOpCategory.Others,
            // 0x58
            GlosOpCategory.LoadArgument, 
            GlosOpCategory.LoadLocalVariable, 
            GlosOpCategory.StoreLocalVariable, 
            GlosOpCategory.NotUsed,
            GlosOpCategory.LoadArgument, 
            GlosOpCategory.LoadLocalVariable, 
            GlosOpCategory.StoreLocalVariable, 
            GlosOpCategory.NotUsed,
            // 0x60
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x68
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x70
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x78
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x80
            GlosOpCategory.Branch, 
            GlosOpCategory.Branch, 
            GlosOpCategory.Branch, 
            GlosOpCategory.Branch,
            GlosOpCategory.Branch, 
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed,
            // 0x88
            GlosOpCategory.Branch,
            GlosOpCategory.Branch,
            GlosOpCategory.Branch,
            GlosOpCategory.Branch,
            GlosOpCategory.Branch,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x90
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0x98
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xa0
            GlosOpCategory.Others,
            GlosOpCategory.Others,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xa8
            GlosOpCategory.Others,
            GlosOpCategory.Others,
            GlosOpCategory.Others,
            GlosOpCategory.Others,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xb0
            GlosOpCategory.ShpRv,
            GlosOpCategory.ShpRv,
            GlosOpCategory.ShpRv, 
            GlosOpCategory.ShpRv,
            GlosOpCategory.ShpRv,
            GlosOpCategory.ShpRv,
            GlosOpCategory.NotUsed, 
            GlosOpCategory.NotUsed,
            // 0xb8
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xc0
            GlosOpCategory.Others,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xc8
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xd0
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xd8
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xe0
            GlosOpCategory.Syscall, 
            GlosOpCategory.Syscall, 
            GlosOpCategory.Syscall, 
            GlosOpCategory.Syscall,
            GlosOpCategory.Syscall, 
            GlosOpCategory.Syscall, 
            GlosOpCategory.Syscall, 
            GlosOpCategory.Syscall,
            // 0xe8
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xf0
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            // 0xf8
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
            GlosOpCategory.NotUsed,
        };

        public static GlosOpImmediate[] Immediates { get; } = {
            // 0x00
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x08
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x10
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x18
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x20
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x28
            GlosOpImmediate.Dword, GlosOpImmediate.Dword, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.Byte, GlosOpImmediate.Byte, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x30
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            GlosOpImmediate.Qword, GlosOpImmediate.Dword, GlosOpImmediate.Byte, GlosOpImmediate.None,
            // 0x38
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.Qword, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x40
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            // 0x48
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            // 0x50
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            GlosOpImmediate.Dword, GlosOpImmediate.Dword, GlosOpImmediate.Dword, GlosOpImmediate.None,
            // 0x58
            GlosOpImmediate.Byte, GlosOpImmediate.Byte, GlosOpImmediate.Byte, GlosOpImmediate.None,
            GlosOpImmediate.OnStack, GlosOpImmediate.OnStack, GlosOpImmediate.OnStack, GlosOpImmediate.None,
            // 0x60
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x68
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x70
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x78
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x80
            GlosOpImmediate.Dword, GlosOpImmediate.Dword, GlosOpImmediate.Dword, GlosOpImmediate.Dword,
            GlosOpImmediate.Dword, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x88
            GlosOpImmediate.Byte, GlosOpImmediate.Byte, GlosOpImmediate.Byte, GlosOpImmediate.Byte,
            GlosOpImmediate.Byte, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x90
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0x98
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xa0
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xa8
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xb0
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            GlosOpImmediate.Dword, GlosOpImmediate.Byte, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xb8
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xc0
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xc8
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xd0
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xd8
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xe0
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded, GlosOpImmediate.Embedded,
            // 0xe8
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xf0
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            // 0xf8
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
            GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None, GlosOpImmediate.None,
        };
    }
}
